name: Docker CI/CD

on:
  push:
    branches: ["main"]  # Trigger on pushes to main
  pull_request:         # Trigger on PRs to main
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: |
          docker build -t my-node-app:${{ github.sha }} .

      - name: Run tests
        run: |
          docker run my-node-app:${{ github.sha }} npm test  # Example test command

      - name: Push to Docker Hub
        run: |
          docker tag my-node-app:${{ github.sha }} your-dockerhub-username/my-node-app:${{ github.sha }}
          docker push your-dockerhub-username/my-node-app:${{ github.sha }}

      - name: Logout of Docker Hub
        run: docker logout